"""Builds the whole estate: every member, the answer key and the horror catalog.

An app is data (see generator/apps/): its programs, copybooks, JCL, procs, BMS, CSD and
DCLGEN as specs. This module places each member where a z/OS export would put it,
resolves COPY / CALL / EXEC PGM across the estate, renders, and collects the facts.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Optional

from . import FORMAT, VERSION
from .cobol import write_copybook, write_program
from .data import Item
from .model import CHANNELS, Member
from .other import symbolic_map, write_bms, write_csd, write_dclgen, write_jcl

# library -> file extension, as GitGalaxy (and most exporters) recognise members
EXT = {"cobol": ".cbl", "copybook": ".cpy", "jcl": ".jcl", "proclib": ".prc", "bms": ".bms", "csd": ".csd",
       "dclgen": ".dcl", "copylib": ".cpy"}
LANG = {"cobol": "cobol", "copybook": "cobol", "copylib": "cobol", "dclgen": "cobol", "jcl": "jcl",
        "proclib": "jcl", "bms": "bms", "csd": "csd"}


def member_path(app: Optional[str], library: str, member: str) -> str:
    if len(member) > 8 or member != member.upper():
        raise ValueError(f"{member}: a PDS member name is 1-8 uppercase characters")
    base = f"apps/{app}" if app else "shared"
    return f"{base}/{library}/{member}{EXT[library]}"


class Estate:
    def __init__(self, apps: list[dict[str, Any]], shared: dict[str, Any], horrors: list[dict[str, Any]],
                 seed: int, size: str) -> None:
        self.apps = apps
        self.shared = shared
        self.horror_defs = {h["id"]: h for h in horrors}
        self.seed = seed
        self.size = size
        self.members: dict[str, Member] = {}
        self.program_paths: dict[str, str] = {}
        # copybook member -> [(path, items)] per search scope
        self.copybooks: dict[tuple[Optional[str], str], tuple[str, list[Item]]] = {}

    # ------------------------------------------------------------ registry
    def _register(self) -> None:
        for app in self.apps:
            a = app["id"]
            for p in app.get("programs", []):
                if p["program_id"] in self.program_paths:
                    raise ValueError(f"PROGRAM-ID {p['program_id']} defined twice")
                self.program_paths[p["program_id"]] = member_path(a, "cobol", p["member"])
            for cb in app.get("copybooks", []):
                self.copybooks[(a, cb["member"])] = (member_path(a, "copybook", cb["member"]), cb["items"])
            for bms in app.get("bms", []):
                self.copybooks[(a, bms["mapset"])] = (member_path(a, "copybook", bms["mapset"]), symbolic_map(bms))
            for d in app.get("dclgen", []):
                self.copybooks[(a, d["member"])] = (member_path(a, "dclgen", d["member"]), [])
        for cb in self.shared.get("copylib", []):
            self.copybooks[(None, cb["member"])] = (member_path(None, "copylib", cb["member"]), cb["items"])

    def resolver(self, app: Optional[str]):
        """SYSLIB order: the app's copybook / DCLGEN libraries, then shared/copylib."""

        def resolve(member: str) -> tuple[Optional[str], Optional[list[Item]]]:
            for scope in (app, None):
                hit = self.copybooks.get((scope, member))
                if hit:
                    return hit
            return None, None

        return resolve

    def _new(self, app: Optional[str], library: str, member: str, numbered: bool = False) -> Member:
        path = member_path(app, library, member)
        if path in self.members:
            raise ValueError(f"{path} written twice")
        m = Member(path, LANG[library], app=app, library=library, numbered=numbered)
        self.members[path] = m
        return m

    # ------------------------------------------------------------ build
    def build(self) -> None:
        self._register()
        for app in self.apps:
            a = app["id"]
            resolve = self.resolver(a)
            for cb in app.get("copybooks", []):
                write_copybook(self._new(a, "copybook", cb["member"], cb.get("numbered", False)), cb, resolve)
            for bms in app.get("bms", []):
                write_bms(self._new(a, "bms", bms["mapset"]), bms)
                sym = {"header": [f" SYMBOLIC MAP FOR MAPSET {bms['mapset']} -- GENERATED BY BMS ASSEMBLY"],
                       "items": symbolic_map(bms)}
                sm = self._new(a, "copybook", bms["mapset"])
                write_copybook(sm, sym, resolve)
                sm.generated_from = member_path(a, "bms", bms["mapset"])
            for d in app.get("dclgen", []):
                write_dclgen(self._new(a, "dclgen", d["member"]), d)
            for p in app.get("programs", []):
                write_program(self._new(a, "cobol", p["member"], p.get("numbered", False)), p, resolve,
                              self.program_paths)
            for j in app.get("jcl", []):
                write_jcl(self._new(a, "jcl", j["name"]), j, self.program_paths, proc=False)
            for pr in app.get("procs", []):
                write_jcl(self._new(a, "proclib", pr["name"]), pr, self.program_paths, proc=True)
            for c in app.get("csd", []):
                write_csd(self._new(a, "csd", c["group"]), c, self.program_paths)
        resolve = self.resolver(None)
        for cb in self.shared.get("copylib", []):
            write_copybook(self._new(None, "copylib", cb["member"]), cb, resolve)
        for pr in self.shared.get("proclib", []):
            write_jcl(self._new(None, "proclib", pr["name"]), pr, self.program_paths, proc=True)
        self._link_generated()
        self._link_dependents()
        self._check_horrors()

    def _link_dependents(self) -> None:
        """A call site whose target program's identity is itself a planted horror (H-0008)
        resolves only once that horror is fixed: mark it `depends_on`, so the scorer can show
        it as that horror's cascade rather than as an unexplained failure."""
        for m in self.members.values():
            for f in m.facts.get("call_sites", []):
                target = self.members.get(f.get("resolves_to") or "")
                tags = sorted({p["horror"] for p in (target.facts.get("programs", []) if target else []) if p.get("horror")})
                if tags and f.get("horror") not in tags:
                    f["depends_on"] = tags

    def _link_generated(self) -> None:
        """A COPY of a generated member (a BMS symbolic map) may also be answered by the member
        it is generated from: the import may name either."""
        for m in self.members.values():
            for f in m.facts.get("copies", []):
                target = self.members.get(f["resolves_to"]) if f["resolves_to"] else None
                if target is not None and target.generated_from:
                    f["alternatives"] = [target.generated_from]

    def _check_horrors(self) -> None:
        used = set().union(*(m.horrors for m in self.members.values()))
        unknown = used - set(self.horror_defs)
        if unknown:
            raise ValueError(f"facts tagged with undefined horrors: {sorted(unknown)}")
        unplanted = [h for h, d in self.horror_defs.items() if h not in used and d.get("planted", True)]
        if unplanted:
            raise ValueError(f"horrors defined but never planted: {unplanted}")

    # ------------------------------------------------------------ output
    def files(self) -> dict[str, str]:
        """Every generated file, repo-relative path -> text. Deterministic for a given seed/size."""
        out: dict[str, str] = {}
        for path, m in sorted(self.members.items()):
            out[f"estate/{path}"] = m.text()
        by_app: dict[str, dict[str, Any]] = {}
        manifest_members: dict[str, Any] = {}
        for path, m in sorted(self.members.items()):
            scope = m.app or "_shared"
            by_app.setdefault(scope, {})[path] = m.key_entry()
            manifest_members[path] = {
                "app": m.app,
                "library": m.library,
                "language": m.language,
                "sha256": hashlib.sha256(m.text().encode("utf-8")).hexdigest(),
                "key": f"key/apps/{scope}.json",
                "compile": m.compile,
                **({"generated_from": m.generated_from} if m.generated_from else {}),
                **({"horrors": sorted(m.horrors)} if m.horrors else {}),
            }
        for scope, members in sorted(by_app.items()):
            out[f"key/apps/{scope}.json"] = dump({"format": FORMAT, "app": None if scope == "_shared" else scope,
                                                  "members": members})
        totals = {ch: sum(len(m.facts.get(ch, [])) for m in self.members.values()) for ch in CHANNELS}
        totals["phantoms"] = sum(len(m.phantoms) for m in self.members.values())
        out["key/manifest.json"] = dump({
            "format": FORMAT,
            "generator": {"version": VERSION, "seed": self.seed, "size": self.size},
            "estate_root": "estate",
            "apps": [{"id": a["id"], "title": a["title"], "style": a.get("style", "")} for a in self.apps],
            "channels": list(CHANNELS),
            "fact_totals": totals,
            "horrors": sorted(self.horror_defs),
            "members": manifest_members,
        })
        for hid, d in sorted(self.horror_defs.items()):
            out[f"horrors/{hid}.json"] = dump(self._horror_record(hid, d))
        out["horrors/README.md"] = self._horror_index()
        return out

    def _horror_record(self, hid: str, d: dict[str, Any]) -> dict[str, Any]:
        planted: list[dict[str, Any]] = []
        for path, m in sorted(self.members.items()):
            if hid not in m.horrors:
                continue
            facts = {ch: [f for f in m.facts.get(ch, []) if f.get("horror") == hid] for ch in CHANNELS}
            planted.append({
                "member": path,
                "compile": m.compile,
                "expected": {ch: v for ch, v in facts.items() if v},
                "phantoms": [p for p in m.phantoms if p.get("horror") == hid],
            })
        return {"format": "estate-crucible-horror/1", **d, "planted": planted}

    def _horror_index(self) -> str:
        rows = ["# Horror catalog", "",
                "Generated by `python3 -m generator`; do not edit. Each `H-*.json` holds the horror's",
                "definition (from `spec/horrors.json`), the members it is planted in, and the expected",
                "facts and phantoms the answer key carries for it.", "",
                "| id | issue | category | title | planted in |", "|---|---|---|---|---|"]
        for hid, d in sorted(self.horror_defs.items()):
            where = ", ".join(f"`{p}`" for p, m in sorted(self.members.items()) if hid in m.horrors)
            issue = f"[#{d['issue']}](https://github.com/squid-protocol/gitgalaxy/issues/{d['issue']})" if d.get("issue") else ""
            rows.append(f"| {hid} | {issue} | {d['category']} | {d['title']} | {where} |")
        return "\n".join(rows) + "\n"


def dump(obj: Any) -> str:
    return json.dumps(obj, indent=1, sort_keys=False, ensure_ascii=False) + "\n"


def write_tree(files: dict[str, str], root: Path) -> None:
    for rel, text in files.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(text.encode("utf-8"))
