      * SYMBOLIC MAP FOR MAPSET CUSTMS -- GENERATED BY BMS ASSEMBLY
       01  CUSTMAPI.
           02  FILLER                 PIC X(12).
           02  CUSTIDL                PIC S9(4) COMP.
           02  CUSTIDF                PIC X.
           02  FILLER                 REDEFINES CUSTIDF.
               03  CUSTIDA                PIC X.
           02  CUSTIDI                PIC X(8).
           02  CUSTNML                PIC S9(4) COMP.
           02  CUSTNMF                PIC X.
           02  FILLER                 REDEFINES CUSTNMF.
               03  CUSTNMA                PIC X.
           02  CUSTNMI                PIC X(30).
           02  CUSTBALL               PIC S9(4) COMP.
           02  CUSTBALF               PIC X.
           02  FILLER                 REDEFINES CUSTBALF.
               03  CUSTBALA               PIC X.
           02  CUSTBALI               PIC X(15).
           02  MSGL                   PIC S9(4) COMP.
           02  MSGF                   PIC X.
           02  FILLER                 REDEFINES MSGF.
               03  MSGA                   PIC X.
           02  MSGI                   PIC X(79).
       01  CUSTMAPO               REDEFINES CUSTMAPI.
           02  FILLER                 PIC X(12).
           02  FILLER                 PIC X(3).
           02  CUSTIDO                PIC X(8).
           02  FILLER                 PIC X(3).
           02  CUSTNMO                PIC X(30).
           02  FILLER                 PIC X(3).
           02  CUSTBALO               PIC X(15).
           02  FILLER                 PIC X(3).
           02  MSGO                   PIC X(79).
